# Generated by Django 5.0.6 on 2024-06-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
